version: '3.8'
services:
  app:
    image: leocavalcante/dwoole:dev
    volumes:
      - ./:/app
    environment:
      - ENTRY_POINT_FILE=/app/srv/swoole.php
  caddy:
    image: caddy/caddy
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
  database:
    image: tarantool/tarantool
    environment:
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER_NAME=root
      - TARANTOOL_USER_PASSWORD=secret
    ports:
      - "3301:3301"
    volumes:
      - db_data:/var/lib/tarantool
volumes:
  db_data:
